name: 1st workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: windows-latest
    
    steps:
      - name: Print Welcome Message
        run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Log Directory Files
        run: dir
